[package]
name = "cloudflare_speedtest_slave"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volo-gen = { path = "./volo-gen" }
volo = { version = "0.10.1", features = [ "native-tls" ] }
volo-grpc = { version = "0.10.0", features = [ "native-tls" ] }
pilota.workspace = true

anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
log = "0.4.22"
fastping-rs = "0.2.4"
simple_logger = "5.0.0"
once_cell = "1.19.0"
faststr = "0.2.19"
volo-http = "0.2.8"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false

[workspace]
members = ["volo-gen"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
# we recommend to use the latest framework version for new features and bug fixes
volo = "*"
volo-build = "*"
volo-grpc = "*"
pilota = "*"

anyhow = "1"
futures = "0.3"
tokio = "1"

[features]
__tls = []
rustls = ["__tls", "volo/rustls", "volo-grpc/rustls"]
native-tls = [
    "__tls",
    "volo/native-tls",
    "volo-grpc/native-tls",
#    "volo-http/native-tls",
]
native-tls-vendored = [
    "__tls",
    "volo/native-tls-vendored",
    "volo-grpc/native-tls-vendored",
#    "volo-http/native-tls-vendored",
]
