[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes musl musl-dev musl-tools protobuf-compiler"
]

[target.x86_64-apple-darwin]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes protobuf-compiler"
]

[target.aarch64-apple-darwin]
pre-build = [
    "apt-get update",
    "apt-get install --assume-yes protobuf-compiler"
]