name: Rust Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux_x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
            bin: CloudflareSpeedtest-Slave
            name: CloudflareSpeedtest-Slave-linux-x86_64.tar.gz
            command: build

          - release_for: linux_aarch64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-musl
            bin: CloudflareSpeedtest-Slave
            name: CloudflareSpeedtest-Slave-linux-aarch64.tar.gz
            command: build

          - release_for: darwin_x86_64
            os: ubuntu-22.04
            target: x86_64-apple-darwin
            bin: CloudflareSpeedtest-Slave
            name: CloudflareSpeedtest-Slave-darwin-x86_64.tar.gz
            command: build

          - release_for: darwin_aarch64
            os: ubuntu-22.04
            target: aarch64-apple-darwin
            bin: CloudflareSpeedtest-Slave
            name: CloudflareSpeedtest-Slave-darwin-aarch64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Lib
        run: sudo apt update && sudo apt install -y protobuf-compiler musl-tools musl-dev musl
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: CloudflareSpeedtest-Slave-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
