
on:
  push:
    branches: [ main ] # 或者使用 'master'

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: CloudflareSpeedtest-Slave.exe
            name: CloudflareSpeedtest-Slave-Windows-x86_64.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: CloudflareSpeedtest-Slave-Master
            name: CloudflareSpeedtest-Slave-Master-Darwin-x86_64.tar.gz
            command: both

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: CloudflareSpeedtest-Slave-Master
            name: CloudflareSpeedtest-Slave-Master-Linux-x86_64.tar.gz
            command: both
            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
